Repository TR1LL1ON/TR1LL1ON_FE, pull requests merged in 2023-11, with the labels that each got.

#2 Refactor: 메인 레이아웃 구조 변경
  src/index.css
  src/pages/cart/cart.tsx
  src/pages/detail/detail.tsx
  src/pages/main/main.tsx
  src/pages/mypage/mypage.tsx
  src/pages/payment/payment.tsx
  src/router/mainRouter.tsx
Labels: enhancement

#7 Chore: ThemeProvider 추가
  package.json
  src/App.tsx
  src/style/styled.d.ts
  src/style/theme.ts
  yarn.lock
Labels: enhancement

#16 [UI] 결제 페이지 UI 구현
  custom.d.ts
  package.json
  src/assets/arrow-down.svg
  src/components/template/payment/index.tsx
  src/hooks/useClickOutside.ts
  src/index.css
  src/pages/payment/payment.tsx
  src/style/payment/paymentAnimation.ts
  src/style/payment/paymentStyle.ts
  src/style/styled.d.ts
  src/style/theme.ts
  tsconfig.json
  yarn.lock
Labels: UI

#20 Feat: 로그인/회원가입 UI 구현
  src/components/layout/modal/accountModal.tsx
  src/components/layout/modal/joinModal.tsx
  src/components/layout/modal/loginModal.tsx
  src/components/template/account/Overlay.tsx
  src/components/template/account/SignIn.tsx
  src/components/template/account/SignUp.tsx
  src/components/template/join/.gitkeep
  src/index.css
  src/style/account/AccountStyle.ts
  src/style/join/joinStyle.ts
Labels: UI

#27 Feature/#24
  package.json
  src/assets/searchIcon.svg
  src/components/layout/header.tsx
  src/components/template/payment/AddCreditCard.tsx
  src/components/template/payment/PaymentOptionItem.tsx
  src/components/template/payment/PaymentOptions.tsx
  src/style/header/headerStyle.ts
  src/style/payment/paymentModal.ts
  src/style/payment/paymentStyle.ts
  yarn.lock
Labels: UI

#29 메인 페이지 카테고리 UI 디자인
  package.json
  src/components/template/main/category/MainCategory.tsx
  src/components/template/main/category/categoryList.ts
  src/pages/main/main.tsx
  src/style/header/headerStyle.ts
  src/style/main/mainCategory.ts
  yarn.lock
Labels: UI

#31 장바구니 UI 구현
  src/components/template/cart/.gitkeep
  src/components/template/cart/CartCard.tsx
  src/components/template/cart/CartDetail.tsx
  src/components/template/cart/CartList.tsx
  src/components/template/cart/CartListController.tsx
  src/components/template/cart/index.tsx
  src/pages/cart/cart.tsx
  src/style/cart/cartStyle.ts
Labels: UI

#35 msw 구현
  package.json
  public/mockServiceWorker.js
  src/api/service.ts
  src/components/template/detail/RoomCard.tsx
  src/components/template/detail/detailModal/carousel.tsx
  src/components/template/detail/detailModal/detailModal.tsx
  src/components/template/main/index.tsx
  src/constant.ts
  src/hooks/.gitkeep
  src/interfaces/interface.ts
  src/main.tsx
  src/mocks/browser.ts
  src/mocks/handlers.ts
  src/pages/detail/detail.tsx
  tsconfig.json
  yarn.lock
Labels: ✅ Test

#36 로그인/회원가입 유효성 검사 UI, 기능 구현
  src/components/layout/modal/accountModal.tsx
  src/components/template/account/SignIn.tsx
  src/components/template/account/SignUp.tsx
  src/components/template/account/index.tsx
  src/style/account/AccountStyle.ts
Labels: 🎨 UI, ✨ Feature

#39 숙소 상세 페이지 이미지모달, 아이콘, 리뷰 UI 추가
  src/components/layout/modal/ModalContainer.tsx
  src/components/layout/modal/amenityModal.tsx
  src/components/template/detail/AccommodationInfo.tsx
  src/components/template/detail/DetailContainer.tsx
  src/components/template/detail/DetailService.tsx
  src/components/template/detail/FacilityModal.tsx
  src/components/template/detail/GuestModal/guestModal.tsx
  src/components/template/detail/ImageContainer.tsx
  src/components/template/detail/ImageModal.tsx
  src/components/template/detail/Review.tsx
  src/style/detail/commonModalStyles.ts
  src/style/detail/detailStyle.ts
  src/util/clipboard.ts
Labels: 🎨 UI

#43 마이페이지 UI 구현
  src/components/template/mypage/.gitkeep
  src/components/template/mypage/index.tsx
  src/components/template/mypage/reservationCard.tsx
  src/components/template/mypage/reservationList.tsx
  src/components/template/mypage/wishCard.tsx
  src/components/template/mypage/wishList.tsx
  src/components/template/payment/.gitkeep
  src/pages/mypage/mypage.tsx
Labels: 🎨 UI

#49 Feature/#48
  src/api/service.ts
  src/components/layout/Button/cartBtn.tsx
  src/components/layout/header.tsx
  src/components/layout/modal/DatePicker.tsx
  src/components/layout/modal/ModalContainer.tsx
  src/components/layout/modal/accountModal.tsx
  src/components/template/account/Overlay.tsx
  src/components/template/account/SignIn.tsx
  src/components/template/account/SignUp.tsx
  src/components/template/account/index.tsx
  src/components/template/cart/CartCard.tsx
  src/components/template/cart/CartDetail.tsx
  src/components/template/cart/CartList.tsx
  src/components/template/cart/CartListController.tsx
  src/components/template/cart/index.tsx
  src/components/template/detail/AccommodationInfo.tsx
  src/components/template/detail/DetailContainer.tsx
  src/components/template/detail/DetailService.tsx
  src/components/template/detail/FacilityModal.tsx
  src/components/template/detail/GuestModal/guestAgeGroup.tsx
  src/components/template/detail/GuestModal/guestContent.tsx
  src/components/template/detail/GuestModal/guestModal.tsx
  src/components/template/detail/ImageContainer.tsx
  src/components/template/detail/ImageModal.tsx
  src/components/template/detail/ImageSlideModal.tsx
  src/components/template/detail/Review.tsx
  src/components/template/detail/RoomCard.tsx
  src/components/template/detail/detailModal/detailModal.tsx
  src/components/template/main/category/MainCategory.tsx
  src/components/template/main/index.tsx
  src/components/template/mypage/index.tsx
  src/components/template/mypage/reservationCard.tsx
  src/components/template/mypage/reservationList.tsx
  src/components/template/mypage/wishCard.tsx
  src/components/template/mypage/wishList.tsx
  src/components/template/payment/AddCreditCard.tsx
  src/components/template/payment/PaymentDetail.tsx
  src/components/template/payment/PaymentOptionItem.tsx
  src/components/template/payment/PaymentOptions.tsx
  src/components/template/payment/PaymentReservations.tsx
  src/components/template/payment/PaymentRoomItem.tsx
  src/components/template/payment/PaymentRoomList.tsx
  src/components/template/payment/PaymentTerms.tsx
  src/components/template/payment/index.tsx
  src/mocks/handlers.ts
  src/pages/cart/cart.tsx
  src/pages/detail/detail.tsx
  src/pages/main/main.tsx
  src/pages/mypage/mypage.tsx
  src/pages/payment/payment.tsx
  src/router/mainRouter.tsx
  src/style/cart/cartStyle.ts
  src/style/detail/detailStyle.ts
  src/style/header/headerStyle.ts
  src/style/main/mainCategory.ts
  src/style/payment/paymentStyle.ts
  tsconfig.json
  vite.config.ts
Labels: 🌏 Deploy

#53 결제 페이지 카드 등록 기능 추가
  package.json
  src/api/service.ts
  src/components/template/payment/AddCreditCard.tsx
  src/components/template/payment/PaymentOptionItem.tsx
  src/components/template/payment/PaymentOptions.tsx
  src/components/template/payment/PaymentReservations.tsx
  src/components/template/payment/PaymentRoomItem.tsx
  src/components/template/payment/PaymentRoomList.tsx
  src/constants.ts
  src/hooks/useReservations.ts
  src/interfaces/interface.ts
  src/main.tsx
  src/mocks/handlers.ts
  src/states/atom.ts
  src/style/payment/paymentModal.ts
  yarn.lock
Labels: ✨ Feature

#55 상단바 로그인/회원가입 모달 UI 구현
  src/components/layout/header.tsx
  src/components/layout/modal/HeaderModal.tsx
  src/components/layout/modal/accountModal.tsx
  src/components/template/account/SignIn.tsx
  src/components/template/account/index.tsx
  src/constant.ts
  src/style/account/AccountStyle.ts
  src/style/header/headerStyle.ts
Labels: 🎨 UI, ✨ Feature

#66 2차배포
  README.md
  package.json
  src/api/service.ts
  src/components/layout/header.tsx
  src/components/layout/modal/HeaderModal.tsx
  src/components/layout/modal/accountModal.tsx
  src/components/template/account/SignIn.tsx
  src/components/template/account/index.tsx
  src/components/template/detail/DetailContainer.tsx
  src/components/template/detail/ImageContainer.tsx
  src/components/template/detail/ImageModal.tsx
  src/components/template/main/index.tsx
  src/components/template/mypage/reservationList.tsx
  src/components/template/mypage/wishList.tsx
  src/components/template/payment/AddCreditCard.tsx
  src/components/template/payment/PaymentOptionItem.tsx
  src/components/template/payment/PaymentOptions.tsx
  src/components/template/payment/PaymentReservations.tsx
  src/components/template/payment/PaymentRoomItem.tsx
  src/components/template/payment/PaymentRoomList.tsx
  src/components/template/products/AccommodationInfo.tsx
  src/components/template/products/FacilityModal.tsx
  src/components/template/products/GuestModal/guestAgeGroup.tsx
  src/components/template/products/GuestModal/guestContent.tsx
  src/components/template/products/GuestModal/guestModal.tsx
  src/components/template/products/ImageContainer.tsx
  src/components/template/products/ImageSlideModal.tsx
  src/components/template/products/ProductsContainer.tsx
  src/components/template/products/ProductsFacility.tsx
  src/components/template/products/ProductsFacilityList.tsx
  src/components/template/products/Review.tsx
  src/components/template/products/RoomCard.tsx
  src/components/template/products/RoomsFacilityList.tsx
  src/components/template/products/detailModal/carousel.tsx
  src/components/template/products/detailModal/detailModal.tsx
  src/constant.ts
  src/constants.ts
  src/hooks/useGetParams .ts
  src/hooks/useGetQuery.ts
  src/hooks/useReservations.ts
  src/interfaces/interface.ts
  src/main.tsx
  src/mocks/handlers.ts
  src/pages/detail/detail.tsx
  src/pages/products/products.tsx
  src/router/mainRouter.tsx
  src/states/atom.ts
  src/style/account/AccountStyle.ts
  src/style/header/headerStyle.ts
  src/style/payment/paymentModal.ts
  src/style/products/productsStyle.ts
  yarn.lock
Labels: 🌏 Deploy

#72 로그인/회원가입 API & Cart API 적용
  src/api/service.ts
  src/components/layout/modal/accountModal.tsx
  src/components/template/account/SignIn.tsx
  src/components/template/account/SignUp.tsx
  src/components/template/account/index.tsx
  src/components/template/cart/CartCard.tsx
  src/components/template/cart/CartList.tsx
  src/components/template/cart/index.tsx
  src/interfaces/interface.ts
  src/mocks/handlers.ts
Labels: ✨ Feature

#70 지역별, 카테고리별 URL 변경 및 관련 훅 제작
  package.json
  src/api/service.ts
  src/components/LoadingSpinner.tsx
  src/components/layout/header.tsx
  src/components/template/main/category/MainCategory.tsx
  src/components/template/main/region/Region.style.ts
  src/components/template/main/region/index.tsx
  src/components/template/notFound/index.tsx
  src/components/template/payment/AddCreditCard.tsx
  src/components/template/payment/PaymentOptionItem.tsx
  src/components/template/payment/PaymentOptions.tsx
  src/components/template/payment/PaymentReservations.tsx
  src/constants.ts
  src/hooks/useClickOutside.ts
  src/hooks/useFakeLoading.ts
  src/hooks/useProducts.ts
  src/hooks/useUpdatePersonNumber.ts
  src/index.css
  src/interfaces/interface.ts
  src/main.tsx
  src/router/mainRouter.tsx
  src/states/atom.ts
  src/style/header/headerStyle.ts
  src/style/main/mainCategory.ts
  yarn.lock
Labels: ✨ Feature

#75 Remove: 테스트 로그인 버튼 삭제
  src/components/template/main/index.tsx
Labels: 🔨 Refactor

#84 메인 전체 숙소정보 API 연결
  src/api/service.ts
  src/components/template/main/ProductCard.tsx
  src/components/template/main/index.tsx
  src/components/template/mypage/wishCard.tsx
  src/components/template/products/ProductsContainer.tsx
  src/hooks/useReservations.ts
  src/pages/products/products.tsx
  src/style/main/productCardStyle.ts
Labels: 📬 API

#80 쿠키 저장, prefix 에러 수정
  src/components/template/account/SignIn.tsx
  src/components/template/account/SignUp.tsx
  src/style/account/AccountStyle.ts
  src/util/util.ts
Labels: ✨ Feature, 🐞 BugFix

#82 장바구니 선택 상품 결제페이지로 이동
  src/components/template/cart/CartList.tsx
  src/components/template/cart/index.tsx
Labels: ✨ Feature

#95 장바구니 기능 구현
  src/api/service.ts
  src/components/layout/Button/cartBtn.tsx
  src/components/layout/modal/CartModal.tsx
  src/components/template/cart/CartCard.tsx
  src/components/template/cart/CartDetail.tsx
  src/components/template/cart/CartDetailCard.tsx
  src/components/template/cart/CartList.tsx
  src/components/template/cart/CartListController.tsx
  src/components/template/cart/index.tsx
  src/components/template/products/RoomCard.tsx
  src/hooks/useAddCart.ts
  src/interfaces/interface.ts
Labels: ✨ Feature

#96 룸카드, 숙소상세 모달 API적용
  src/api/service.ts
  src/components/template/mypage/index.tsx
  src/components/template/mypage/reservationAccordion.tsx
  src/components/template/mypage/reservationCard.tsx
  src/components/template/mypage/reservationList.tsx
  src/components/template/mypage/reviewWriteModal.tsx
  src/components/template/products/ProductsContainer.tsx
  src/interfaces/interface.ts
  src/util/util.ts
Labels: 📬 API

#102 숙소상세보기 데이터패칭, UI 리팩토링
  src/components/template/mypage/reservationAccordion.tsx
  src/components/template/mypage/reservationCard.tsx
  src/components/template/products/ProductsContainer.tsx
  src/components/template/products/RoomCard.tsx
  src/components/template/products/detailModal/detailModal.tsx
  src/interfaces/interface.ts
Labels: 🎨 UI, 📬 API, 🔨 Refactor

#104 숙소 데이터 받아오기 및 결제 API 연동
  src/api/service.ts
  src/components/template/cart/CartDetailCard.tsx
  src/components/template/cart/index.tsx
  src/components/template/payment/PaymentDetail.tsx
  src/components/template/payment/PaymentReservations.tsx
  src/components/template/payment/PaymentRoomItem.tsx
  src/components/template/payment/PaymentRoomList.tsx
  src/components/template/payment/index.tsx
  src/constants.ts
  src/hooks/useFilteredReservation.ts
  src/hooks/useReservations.ts
Labels: ✨ Feature, 📬 API

#105 숙소, 객실상세 예약하기버튼 로직변경
  src/components/template/products/RoomCard.tsx
  src/components/template/products/detailModal/detailModal.tsx
  src/interfaces/interface.ts
Labels: 🔨 Refactor

#106 로그아웃 API 적용, PrivateRoute 생성
  src/api/service.ts
  src/components/layout/PrivateRoute.tsx
  src/components/layout/modal/HeaderModal.tsx
  src/components/template/cart/EmptyCart.tsx
  src/components/template/cart/index.tsx
  src/router/mainRouter.tsx
  src/util/util.ts
Labels: ✨ Feature, 📬 API

#107 3차배포
  src/api/service.ts
  src/components/layout/Button/cartBtn.tsx
  src/components/layout/PrivateRoute.tsx
  src/components/layout/modal/CartModal.tsx
  src/components/layout/modal/DatePicker.tsx
  src/components/layout/modal/HeaderModal.tsx
  src/components/layout/modal/ModalContainer.tsx
  src/components/template/account/SignIn.tsx
  src/components/template/account/SignUp.tsx
  src/components/template/cart/CartCard.tsx
  src/components/template/cart/CartDetail.tsx
  src/components/template/cart/CartDetailCard.tsx
  src/components/template/cart/CartList.tsx
  src/components/template/cart/CartListController.tsx
  src/components/template/cart/EmptyCart.tsx
  src/components/template/cart/index.tsx
  src/components/template/main/ProductCard.tsx
  src/components/template/main/index.tsx
  src/components/template/mypage/index.tsx
  src/components/template/mypage/reservationAccordion.tsx
  src/components/template/mypage/reservationCard.tsx
  src/components/template/mypage/reservationList.tsx
  src/components/template/mypage/reviewWriteModal.tsx
  src/components/template/mypage/wishCard.tsx
  src/components/template/payment/PaymentDetail.tsx
  src/components/template/payment/PaymentReservations.tsx
  src/components/template/payment/PaymentRoomItem.tsx
  src/components/template/payment/PaymentRoomList.tsx
  src/components/template/payment/index.tsx
  src/components/template/products/AccommodationInfo.tsx
  src/components/template/products/AllFacility.tsx
  src/components/template/products/FacilityModal.tsx
  src/components/template/products/GuestModal/guestAgeGroup.tsx
  src/components/template/products/GuestModal/guestContent.tsx
  src/components/template/products/GuestModal/guestModal.tsx
  src/components/template/products/ImageContainer.tsx
  src/components/template/products/ImageSlideModal.tsx
  src/components/template/products/ModalTab.tsx
  src/components/template/products/NoticeModal.tsx
  src/components/template/products/ProductsContainer.tsx
  src/components/template/products/ProductsFacility.tsx
  src/components/template/products/ProductsFacilityList.tsx
  src/components/template/products/RoomCard.tsx
  src/components/template/products/RoomsFacilityList.tsx
  src/components/template/products/detailModal/detailModal.tsx
  src/components/template/products/iconAndTextMapping.tsx
  src/constants.ts
  src/hooks/useAddCart.ts
  src/hooks/useFilteredReservation.ts
  src/hooks/useReservations.ts
  src/hooks/useUpdatePersonNumber.ts
  src/interfaces/interface.ts
  src/mocks/handlers.ts
  src/pages/products/products.tsx
  src/router/mainRouter.tsx
  src/states/atom.ts
  src/style/account/AccountStyle.ts
  src/style/main/productCardStyle.ts
  src/style/products/productsStyle.ts
  src/util/util.ts
Labels: 🌏 Deploy

#130 마이페이지 예약내역에서 리뷰작성 구현
  src/api/service.ts
  src/components/template/main/index.tsx
  src/components/template/mypage/reservationAccordion.tsx
  src/components/template/mypage/reservationCard.tsx
  src/components/template/mypage/reviewWriteModal.tsx
  src/interfaces/interface.ts
Labels: ✨ Feature

#138 Dev
  package.json
  src/api/service.ts
  src/components/layout/Button/cartBtn.tsx
  src/components/layout/footer.tsx
  src/components/layout/header.tsx
  src/components/layout/modal/HeaderModal.tsx
  src/components/layout/modal/MapModal.tsx
  src/components/layout/modal/MapSearch.tsx
  src/components/template/account/SignIn.tsx
  src/components/template/account/SignUp.tsx
  src/components/template/account/index.tsx
  src/components/template/cart/CartCard.tsx
  src/components/template/cart/CartDetail.tsx
  src/components/template/cart/CartList.tsx
  src/components/template/cart/CartListController.tsx
  src/components/template/cart/index.tsx
  src/components/template/main/category/MainCategory.tsx
  src/components/template/main/index.tsx
  src/components/template/mypage/reservationAccordion.tsx
  src/components/template/mypage/reservationCard.tsx
  src/components/template/mypage/reviewWriteModal.tsx
  src/components/template/products/AccommodationInfo.tsx
  src/components/template/products/FacilityModal.tsx
  src/components/template/products/GuestModal/guestModal.tsx
  src/components/template/products/Map.tsx
  src/components/template/products/ModalTab.tsx
  src/components/template/products/ProductsContainer.tsx
  src/components/template/products/Review.tsx
  src/components/template/products/RoomCard.tsx
  src/components/template/products/detailModal/detailModal.tsx
  src/components/template/products/detailModal/modalReview.tsx
  src/constant.ts
  src/hooks/useDisplayedReview.ts
  src/hooks/useFilteredReservation.ts
  src/hooks/useGetCarts.ts
  src/interfaces/interface.ts
  src/main.tsx
  src/states/atom.ts
  src/style/header/headerStyle.ts
  src/util/geolocation.ts
  vite.config.ts
  yarn.lock
Labels: 🌏 Deploy

#143 Refactor: 상품 바로 예약 시 장바구니 개수 업데이트 & 장바구니 수정
  src/api/service.ts
  src/components/template/cart/CartCard.tsx
  src/components/template/products/RoomCard.tsx
Labels: 🔨 Refactor
