Repository TR1LL1ON/TR1LL1ON_FE, pull requests merged in 2023-12, with the labels that each got.

#155 4차배포
  index.html
  src/App.tsx
  src/api/service.ts
  src/components/template/mypage/reservationAccordion.tsx
  src/components/template/mypage/reservationList.tsx
  src/components/template/products/AccommodationInfo.tsx
  src/components/template/products/ProductsContainer.tsx
  src/components/template/products/RoomCard.tsx
  src/components/template/products/detailModal/detailModal.tsx
  src/constant.ts
  src/main.tsx
  src/states/atom.ts
  src/util/calculateCancellation.ts
  src/util/util.ts
Labels: 🌏 Deploy

#158 리뷰 수정, 삭제 구현
  src/api/service.ts
  src/components/template/mypage/reservationAccordion.tsx
  src/components/template/mypage/reservationCard.tsx
  src/components/template/mypage/reviewWriteModal.tsx
  src/components/template/products/ProductsContainer.tsx
  src/interfaces/interface.ts
  src/util/util.ts
Labels: ✨ Feature

#165 무한스크롤 구현 / 위치기반 리팩토링
  package.json
  src/api/service.ts
  src/components/layout/header.tsx
  src/components/layout/modal/MapSearch.tsx
  src/components/template/main/index.tsx
  src/style/main/productCardStyle.ts
  src/util/fetchCurrentLocation.ts
  yarn.lock
Labels: ✨ Feature, 🔨 Refactor

#156 Refactor: 로그인/회원가입 및 장바구니 react-query 적용 & 로그인 알림 모달 추가
  src/api/service.ts
  src/components/layout/Button/cartBtn.tsx
  src/components/layout/header.tsx
  src/components/layout/modal/HeaderModal.tsx
  src/components/layout/modal/InformSignInModal.tsx
  src/components/layout/modal/accountModal.tsx
  src/components/template/account/SignIn.tsx
  src/components/template/account/SignUp.tsx
  src/components/template/account/index.tsx
  src/components/template/cart/CartCard.tsx
  src/components/template/cart/CartListController.tsx
  src/components/template/cart/index.tsx
  src/components/template/mypage/reviewWriteModal.tsx
  src/components/template/products/RoomCard.tsx
  src/components/template/products/detailModal/detailModal.tsx
  src/hooks/useAddCart.ts
  src/hooks/useGetCarts.ts
  src/interfaces/interface.ts
  src/style/account/AccountStyle.ts
  src/style/header/headerStyle.ts
  src/util/util.ts
Labels: ✨ Feature, 🔨 Refactor

#168 Refator: 로그인관련 리팩토링
  src/api/service.ts
  src/components/layout/Button/cartBtn.tsx
  src/components/layout/header.tsx
  src/components/layout/modal/HeaderModal.tsx
  src/components/layout/modal/InformSignInModal.tsx
  src/components/layout/modal/accountModal.tsx
  src/components/template/account/SignIn.tsx
  src/components/template/account/SignUp.tsx
  src/components/template/account/index.tsx
  src/components/template/cart/CartCard.tsx
  src/components/template/cart/CartListController.tsx
  src/components/template/cart/index.tsx
  src/components/template/mypage/reviewWriteModal.tsx
  src/components/template/products/RoomCard.tsx
  src/components/template/products/detailModal/detailModal.tsx
  src/hooks/useAddCart.ts
  src/hooks/useGetCarts.ts
  src/interfaces/interface.ts
  src/style/account/AccountStyle.ts
  src/style/header/headerStyle.ts
  src/util/util.ts
Labels: 🔨 Refactor

#170 Fix: 로그인 오류 수정
  src/components/template/account/SignIn.tsx
  src/util/util.ts
Labels: 🐞 BugFix

#175 Env: 리펙토링 중간 배포
  package.json
  src/api/service.ts
  src/components/layout/modal/DatePicker.tsx
  src/components/layout/modal/MapSearch.tsx
  src/components/template/main/ProductCard.tsx
  src/components/template/mypage/error.tsx
  src/components/template/mypage/index.tsx
  src/components/template/mypage/reservationAccordion.tsx
  src/components/template/mypage/reservationCard.tsx
  src/components/template/mypage/reservationList.tsx
  src/components/template/mypage/reviewWriteModal.tsx
  src/components/template/mypage/skeletonCard.tsx
  src/components/template/products/AccommodationInfo.tsx
  src/components/template/products/ProductsContainer.tsx
  src/components/template/products/Review.tsx
  src/components/template/products/RoomCard.tsx
  src/components/template/products/detailModal/detailModal.tsx
  src/components/template/products/detailModal/modalReview.tsx
  src/hooks/useDisplayedReview.ts
  src/hooks/useRoomReviews.ts
  src/interfaces/interface.ts
  yarn.lock
Labels: 🌏 Deploy

#177 Env: 리펙토링 배포
  src/components/template/payment/PaymentDetail.tsx
  src/components/template/payment/PaymentOptions.tsx
  src/components/template/payment/PaymentReservations.tsx
  src/components/template/payment/PaymentRoomList.tsx
  src/components/template/payment/index.tsx
  src/components/template/payment/paymentConfirm/index.tsx
  src/components/template/payment/utils/calculateNights.ts
  src/components/template/payment/utils/index.ts
  src/hooks/useFilteredReservation.ts
  src/pages/payment/ErrorFallback.tsx
  src/pages/payment/payment.tsx
Labels: 🌏 Deploy

#178 Feat: Suspense 딜레이추가, 화면전환 깜빡임 해결
  src/components/template/mypage/delayedFallback.tsx
  src/components/template/mypage/reservationList.tsx
Labels: ✨ Feature

#179 Feat: Suspense 딜레이추가, 화면전환 깜빡임 해결
  src/components/template/mypage/delayedFallback.tsx
  src/components/template/mypage/reservationList.tsx
Labels: ✨ Feature

#180 Refetor: 리뷰페이지 리렌더링 제거
  src/components/template/mypage/reservationAccordion.tsx
  src/components/template/mypage/reservationList.tsx
  src/components/template/mypage/reviewWriteModal.tsx
Labels: 🔨 Refactor

#184 번들사이즈 최적화 + 코드스플리팅으로 초기랜더링 개선
  .gitignore
  package.json
  src/components/layout/modal/MapModal.tsx
  src/components/layout/modal/calenderModal.tsx
  src/components/template/products/ProductsContainer.tsx
  src/hooks/useGetParams .ts
  src/hooks/useGetQuery.ts
  src/router/mainRouter.tsx
  yarn.lock
Labels: 🔨 Refactor

#185 번들사이즈 최적화 + 코드스플리팅으로 초기랜더링 개선
  .gitignore
  package.json
  src/components/layout/modal/MapModal.tsx
  src/components/layout/modal/calenderModal.tsx
  src/components/template/products/ProductsContainer.tsx
  src/hooks/useGetParams .ts
  src/hooks/useGetQuery.ts
  src/router/mainRouter.tsx
  yarn.lock
Labels: 🌏 Deploy

#187 Chore: 성능체크를 위한 롤백
  src/components/layout/modal/MapModal.tsx
  src/components/layout/modal/calenderModal.tsx
  src/components/template/products/ProductsContainer.tsx
  src/router/mainRouter.tsx
Labels: 🔨 Refactor

#188 번들링최적화 재도입, 리액트쿼리 로딩스피너 추가
  src/components/layout/modal/MapModal.tsx
  src/components/layout/modal/calenderModal.tsx
  src/components/template/main/index.tsx
  src/components/template/products/ProductsContainer.tsx
  src/components/template/products/detailModal/modalReview.tsx
  src/router/mainRouter.tsx
Labels: 🔨 Refactor

#192 Fix: main 페이지 상품 price null일때 0원으로 대응
  src/components/template/main/ProductCard.tsx
Labels: 🐞 BugFix
